### ISSUE TITLE
I have a single json file for 400 images for bounding boxes. Getting error while converting to pascal voc xml

### ISSUE THREAD

**Issue by pccoe-co** [pylabel-project/samples#4] opened 2022-03-31 10:13 UTC
Hi,
Thank you for making this wonderful package. 
I have a single json file for (constant 100 pixel x 100 pixel pixel) bounding boxes in object detection. I want to convert it into pascal voc xml format. I tried (https://github.com/pylabel-project/samples/blob/main/coco2voc.ipynb) but getting error- " TypeError: list indices must be integers or slices, not str " for my json file. I want to make a xml file for each images. How can i resolve this issue?

link to json and csv file (https://drive.google.com/drive/folders/1WJyCZMDaoroa6K4s4AbZQygFPyyiltKS?usp=sharing)

Thanks.

**Comment by alexheat** [comment] 2022-03-31 22:31
Hi, sorry to hear you have a problem. I will check it out this weekend if not sooner

**Comment by alexheat** [comment] 2022-04-02 15:22
Hello. I took a look at your json file. The problem is that your .json file is not in the coco schema/format. Please take a look at the sample coco json file I use in that notebook and you can also refer to this documentation here https://cocodataset.org/#format-data. 

One other thing that I noticed is that your annotations don't have a height or width. You will need to have a height and a width to create a bounding box. You could try making a fixed height and width like 100px for all of the items if you don't have anything. 

So it looks like you have some work to do to convert these into a standard format. Depending on how many images you have you may be better off relabeling them with a tool that export into the right format.

**Comment by alexheat** [comment] 2022-04-07 04:09
Closing issue since the cause of the error has been identified

**Closed** 2022-04-07 04:10 UTC
